package com.optum.hedis.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.optum.hedis.domain.RunResultsDef;


public interface RunResultsDefRepository extends JpaRepository<RunResultsDef, Long>,JpaSpecificationExecutor<RunResultsDef> {
	String COPY_MEASURE_FROM_CURRENT_YEAR_TO_NEXT_YEAR_IN_RUN_RESULTS_TABLE = "insert into RUN_RESULTS_DEF (RUN_RESULTS_DEF_ID, MEASURE_ID, NUMERATOR_ID, USEINOUTLIERREPORT, ADMIN_RATE, ADMIN_NUM_HITS, ADMIN_DENOM_HITS, HYBRID_RATE, HYBRID_NUM_HITS, HYBRID_DENOM_HITS, HYBRID_ADMIN_HITS, HYBRID_MED_HITS, HYB_ADMIN_NUMERATOR, HYB_ADMIN_RATE, RATE_DATA_TYPE, PRODUCT_LINE, RATE_TYPE, CREAT_TMSTMP, CREAT_USER, UPDT_TMSTMP, UPDT_USER, SUPPLMNTL_NUMERATOR, EXCLUSION_CNT, REQUIRED_ADMIN_EXCLUSION_CNT, REQUIRED_HYBRID_EXCLUSION_CNT, OPTIONAL_ADMIN_EXCLUSION_CNT, OPTIONAL_HYBRID_EXCLUSION_CNT, MEASURE_YEAR) select RUN_RESULTS_DEF_ID, MEASURE_ID, NUMERATOR_ID, USEINOUTLIERREPORT, ADMIN_RATE, ADMIN_NUM_HITS, ADMIN_DENOM_HITS, HYBRID_RATE, HYBRID_NUM_HITS, HYBRID_DENOM_HITS, HYBRID_ADMIN_HITS, HYBRID_MED_HITS, HYB_ADMIN_NUMERATOR, HYB_ADMIN_RATE, RATE_DATA_TYPE, PRODUCT_LINE, RATE_TYPE, CREAT_TMSTMP, CREAT_USER, UPDT_TMSTMP, UPDT_USER, SUPPLMNTL_NUMERATOR, EXCLUSION_CNT, REQUIRED_ADMIN_EXCLUSION_CNT, REQUIRED_HYBRID_EXCLUSION_CNT, OPTIONAL_ADMIN_EXCLUSION_CNT, OPTIONAL_HYBRID_EXCLUSION_CNT, :toYear from RUN_RESULTS_DEF where MEASURE_YEAR = :fromYear";
	String DELETE_MEASURE_IN_CLAIM_TABLE = "delete Claim where measureId = :measureId and measureYear = :selectedYearToDeleteMeasure";
	String GET_RUN_RESULTS_DEF_TABLE = "select '',RUN_RESULTS_DEF_ID,MEASURE_ID,NUMERATOR_ID,HASHYBRID,USEINOUTLIERREPORT,ADMIN_RATE,ADMIN_NUM_HITS,ADMIN_DENOM_HITS,HYBRID_RATE,HYBRID_NUM_HITS,HYBRID_DENOM_HITS,HYBRID_ADMIN_HITS,HYBRID_MED_HITS,HYB_ADMIN_NUMERATOR,HYB_ADMIN_RATE,RATE_DATA_TYPE,PRODUCT_LINE,RATE_TYPE,CREAT_TMSTMP,CREAT_USER,UPDT_TMSTMP,UPDT_USER,SUPPLMNTL_NUMERATOR,EXCLUSION_CNT,REQUIRED_ADMIN_EXCLUSION_CNT,REQUIRED_HYBRID_EXCLUSION_CNT,OPTIONAL_ADMIN_EXCLUSION_CNT,OPTIONAL_HYBRID_EXCLUSION_CNT,MEASURE_YEAR from RUN_RESULTS_DEF order by RUN_RESULTS_DEF_ID";
	String GET_RUN_RESULTS_DEF_FULL_TABLE = "select '',RUN_RESULTS_DEF_ID,MEASURE_ID,NUMERATOR_ID,HASHYBRID,USEINOUTLIERREPORT,ADMIN_RATE,ADMIN_NUM_HITS,ADMIN_DENOM_HITS,HYBRID_RATE,HYBRID_NUM_HITS,HYBRID_DENOM_HITS,HYBRID_ADMIN_HITS,HYBRID_MED_HITS,HYB_ADMIN_NUMERATOR,HYB_ADMIN_RATE,RATE_DATA_TYPE,PRODUCT_LINE,RATE_TYPE,CREAT_TMSTMP,CREAT_USER,UPDT_TMSTMP,UPDT_USER,SUPPLMNTL_NUMERATOR,EXCLUSION_CNT,REQUIRED_ADMIN_EXCLUSION_CNT,REQUIRED_HYBRID_EXCLUSION_CNT,OPTIONAL_ADMIN_EXCLUSION_CNT,OPTIONAL_HYBRID_EXCLUSION_CNT,MEASURE_YEAR from RUN_RESULTS_DEF order by RUN_RESULTS_DEF_ID";
	String GET_RUN_RESULTS_DEF_TABLE_FOR_EXPORT = "select * from RUN_RESULTS_DEF";

	@Query(value = COPY_MEASURE_FROM_CURRENT_YEAR_TO_NEXT_YEAR_IN_RUN_RESULTS_TABLE, nativeQuery = true)
	@Modifying
	void copyMeasure(@Param("fromYear") Long fromYear, @Param("toYear") Long toYear);
	
	@Query(value = DELETE_MEASURE_IN_CLAIM_TABLE)
	@Modifying
	void deleteMeasure(@Param("measureId") Long measureName, @Param("selectedYearToDeleteMeasure") String selectedYearToDeleteMeasure);
	
	@Query(value = GET_RUN_RESULTS_DEF_TABLE, nativeQuery = true)
	List<Object[]> getRunResultsDefTable();
	
	
	@Query(value = GET_RUN_RESULTS_DEF_FULL_TABLE, nativeQuery = true)
	List<Object[]> getRunResultsDefFullTable();
	
	
	@Query(value = GET_RUN_RESULTS_DEF_TABLE_FOR_EXPORT, nativeQuery = true)
	List<Object[]> getRunResultsDefTableForExport();
}
